version: 1.1.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_non_tags: true
before_build:
- cmd: nuget restore src\Cogworks.SiteLock.sln
build:
  project: src/Cogworks.SiteLock.sln
  verbosity: minimal